### ISSUE TITLE
Old instructions link on download page

### ISSUE THREAD

**Issue by cbenhagen** [superdesk/liveblog#326]
`Follow these instructions` on the [download](https://www.sourcefabric.org/en/liveblog/download/) page should point to https://github.com/superdesk/liveblog/blob/master/README.md instead of https://github.com/superdesk/Live-Blog/blob/master/INSTALL.md

**Comment by vied12** [comment]
Thank you for the report ! It will be fixed soon

**Comment by vied12** [comment]
Page updated
