### ISSUE TITLE
running liveblog in production

### ISSUE THREAD

**Issue by a93ushakov** [superdesk/liveblog#334]
Hello,

how to deploy `liveblog` in production server?

At first - `libcontainer` reduces networking perfomance. Solution is using `--net="host"` flag.
But what sources should I edit to change default 80 port? (in my case it's busy)

Also, is it correct simply to `docker-compose up` in `docker` directory?
Why `virtualenv env` must be used? `docker` provides better isolation then `virtualenv`.

**Comment by actionless** [comment]
https://github.com/superdesk/liveblog/issues/335

you can use docker-compose directly without virtualenv, installing docker-compose globally could cause dependency conflicts with some other python libs on some setups

**Comment by fippu82** [comment]
What about the first question? I'm also wondering what it takes to actually run a Live Blog live. ;-) 

Should it still be run in docker (with docker-compose)? What about data persistence?: I had the same issue as described here: https://forum.sourcefabric.org/discussion/18086/liveblog-3-0-on-ubuntu-14-04lts. Seems I was able to fix it though, but I'm not sure if that's the right way (especially for a production environment). Also, I still cannot log-in to the app as the connections to http://[servername.domain]/api are failing with error "502 Bad Gateway".  

Is it correct to change the three Env variables (SUPERDESK_URL, SUPERDESK_WS_URL, SUPERDESK_CLIENT_URL) in common.yml to the public server name/IP? 

Thank you
