### ISSUE TITLE
run LiveBlog without Amathon

### ISSUE THREAD

**Issue by a93ushakov** [superdesk/liveblog#343]
is it possible?

**Comment by vied12** [comment]
Not yet, but this is needed for sure

**Comment by dzogrim** [comment]
Hi @vied12 is it expected that everything has to be pointing to Amazon S3? Each blog embed generate errors as it is trying to load everything (js, css…) from S3, not from configured "SUPERDESK_URL"

**Comment by vied12** [comment]
You should be able to open a blog locally, since all the links are relative in the page.
Use the address `<server_ip>:<port>/embed/<blog_id>`
But you should never publish this url in production.
