### ISSUE TITLE
Cache system : limits and solutions

### ISSUE THREAD

**Issue by vied12** [superdesk/liveblog#57]
## The Problem

Liveblog is a __live__ blogging tool. Because this tool provides live content, it deserves all our attention about how we will setup the cache.  
Currently, the cache system is handled by the web server, Nginx. Then the application Liveblog has no control at all on it. Basically it saves all the responses given by the application by using the url signature as key for every GET and HEAD requests, and provide to the clients the saved response for a given time (15s here) 

Now let's see our application. Liveblog allows the administrator to add/edit/remove posts on each blog. As you know, to notify all users browsers, an event is triggered through *Autobahn* from the back-end (application on the server) to the client's browser.
When the client receive this event, he tries to fetch all the updates. Let's imagine on this url `blog/<blog_id>/posts?updated_since=<since>`.  
If `<since>` is a `change id` provided in the event through *Autobahn*, because change id is incremented at every changes, it will act like a revision number and will by-pass the cache to allow us to fetch the latest changes. Then no problem her with a `change id` and the cache at this point, but when a new update will appear later on the back-end, the response of this url won't provide all the changes but only the ones which were cached.

Keeping in mind the auto update mechanism, we also have a pagination system. When we arrive on the blog page, we fetch the first page by an url like `blog/<blog_id>/posts?page=1`.
Obviously, with the current cache system, a cached response will be returned. Maybe an old one, which won't contain the latest update. And the client won't receive the event through *Autobahn* because it was already sent before the client connects to it.

So now it's obvious we have to take care about the cache, let's find solutions.

Let's keep in mind what is expected for a cache system:

1. a clever cache should not impact too much the way that we develop our application and should have a minimal footprint on it.
1. an efficient cache should return as longer it's possible the cached responses.

### 1. Drop the current cache system to an application level cache system (Edouard)

By using a cache system on the application, we are able to control it deeply.  
It allows us to:

* flush the cache for a unique blog after any update on this blog.
* keep in cache the responses longer than 15s, until any change.
* don't impact the way we use the API on the client side by adding version number or anything to by-pass the cache.  
  All the cache operations are done by the back-end.

Then we are sure that any call to the api will retrieve fresh data. This is, in my opinion, what is expected for a live blogging tool.

#### How it works

1. First, disable the nginx cache system.
1. On the back-end, on the service level, we should set in cache all the responses from the api and return them instead of fetching the resources.
1. On any update, flushing the relative cache.

For the cache service we can use Redis which is already used by Superdesk for queues, or Memcache. IMO, it's good to isolate cache and queue management. In the future we would maybe want to reset all the cache data, or use another service provider in the cloud just for the cache. 

See: http://flask.pocoo.org/docs/0.10/patterns/caching/

### 2. Blog pages with versioning and blog pages snapshot (Mihai)
The basic idea is to change the way the client is updating. Until now the user has a status and it request from server the differences between current client status and current server status. This means different responses for different clients and also different responses in time.
In the new proposal the blog is organized on pages and the client is requesting the status of pages on server(it will be the same response for all clients) and then the client will requests from server the pages that has been changed. Every page will have a version and every time a change will be performed in a page, the version will be increased.
Every time a client starts an update task, first it will request from server the blog snapshot with the version of the pages. The version of the pages snapshot is small and can be stored on redis. The request is not dependent by clients so all clients will receive the same response. The response on this request will change in time so this request can be cached only for short period of time (no more than 30 sec)
After the client receives the pages status, for pages that has old version it will request from the server the new versions, by specifying a given version. All clients will receive the same response and the result will not change in time, so it can be cached for large periods of time.
The difficulty for client is to replace one page version with a new page version. The delete of old elements and the add of the new elements can generate flickering. The idea is to compare the two lists and perform as less as possible operations on the old list.
In current implementation of embed the client receives updates as the following operations: new, modify and delete. By having the two lists we can generate those operations in the following way:
- for all elements that are on old list but not on new list we generate a delete
- for all elements that are on new list but not on old list we generate a new
- for all elements that are on new list and on old list we compare etag and if the tag is not the same we generate an edit

So the old implementation can be used and we just have to add this processing on the received pages.

To request a new page is very simple, the client just request the last version of the page and add it at the end of the list.
The advantage of this solution is that the processing on the server will be reduced(no special processing on every client request) and also the cache management is very simple so on deployment can be used any cache server.
Also creating an offline blog is very simple, we just have to save the generated jsons for pages and blog pages snapshot.
Probably we can use this pagination solution for SEO too, for every page we can generate the HTML.

**Comment by ahilles107** [comment]
### ```The fastest HTTP request is the one not made.``` - [link][1]

I don't like option of disabling nginx caching and relying on our own internal redis/memcache storage only. Internal cache is important but more important is http caching.

How about good usage of various http caching features like - if-not-modified, expires, e-tag headers?

I thing that services popular so much as live blog should always be behind some proxy cachning (varnish, nginx) and designed to be vertically scalable.

[1]: http://www.stevesouders.com/blog/2012/03/22/cache-them-if-you-can/?utm_source=dlvr.it&utm_medium=tumblr

**Comment by ioanpocol** [comment]
Any conclusion on this?

**Comment by vied12** [comment]
We have both. We use cache parameters in header for resources (python Eve handles that), and internal cache for search queries (https://github.com/superdesk/liveblog/pull/131)

**Comment by ioanpocol** [comment]
The point is that the current implementation is not "friendly" for external cache(explained why on the second proposed solution). External cache is far more important for scalability than internal cache. Of course adding internal cache is a good thing but not enough.

**Comment by vied12** [comment]
Which implementation ? The internal cache or the parameters in the Header ?
And can you explain why it's not friendly ?
How do you do with Superdesk ?

**Comment by ioanpocol** [comment]
Ignore my comment, I think the current implementation will work well.
